# Generated by Django 4.1.2 on 2022-12-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=11)),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_auth.radiologistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='images/input/')),
                ('output_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('labels', models.CharField(blank=True, max_length=10000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_app.patient')),
            ],
        ),
    ]
