# Generated by Django 4.1.2 on 2022-12-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0003_alter_scan_input_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
