# Generated by Django 4.1.2 on 2022-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0004_alter_scan_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='input_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
