# Generated by Django 4.1.2 on 2022-12-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0005_alter_scan_input_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/input/'),
        ),
    ]
